# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Pass - Sponsorship (99963bef-cb91-432f-9dc7-073aefa2802f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az config set extension.use_dynamic_install=yes_without_prompt
      az storage container exists --name testcontainer --account-name newstrac --sas-token ?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-04-09T14:46:40Z&st=2022-04-07T06:46:40Z&spr=https&sig=CurCPgm8FSZcGeo5aK6dPUSNo4CIL0UTvMg12gTCZG8%3D