# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go (40783f5c-2558-41a9-a5af-97b47669376e)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #az config set extension.use_dynamic_install=yes_without_prompt
      #az upgrade --yes
      #az storage blob exists -c testcontainer -n sample.txt --account-name newstrac1 --connection-string "DefaultEndpointsProtocol=https;AccountName=newstrac1;AccountKey=E30o0AnPF78lFjtXc7GDq69n2/OtCwoLo+/xjSerYldWrJiZiPRO2EcoaINrvU0oqwFrA6E9qihh+ASt/UjAVg==;EndpointSuffix=core.windows.net"
      ##https://newstrac1.blob.core.windows.net/testcontainer?sp=r&st=2022-04-11T13:14:38Z&se=2022-04-11T21:14:38Z&spr=https&sv=2020-08-04&sr=c&sig=HQuD%2BFD3Cnrk73qi8i5rWw4dxpSHSAk6PyJg9FaZg94%3D
      #--sas-token ?sp=r&st=2022-04-11T13:14:38Z&se=2022-04-11T21:14:38Z&spr=https&sv=2020-08-04&sr=c&sig=HQuD%2BFD3Cnrk73qi8i5rWw4dxpSHSAk6PyJg9FaZg94%3D
      #az storage blob directory exists -c testcontainer -d  testsubdir --account-name newstrac1 --sas-token ?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupx&se=2022-04-09T15:04:28Z&st=2022-04-07T07:04:28Z&spr=https&sig=w5J4vQf0wOUUk2yiU0ysHjdOsYbaLQhVlVtYIUY3Jl4%3D
      #blob sas#az storage blob exists -c testcontainer -n sample.txt --account-name newstrac1 --sas-token ?sp=r&st=2022-04-11T13:14:38Z&se=2022-04-11T21:14:38Z&spr=https&sv=2020-08-04&sr=c&sig=HQuD%2BFD3Cnrk73qi8i5rWw4dxpSHSAk6PyJg9FaZg94%3D
      #blob sas az storage blob exists -c testcontainer -n sample.txt --account-name newstrac1 --sas-token ?sp=r&st=2022-04-11T13:46:07Z&se=2022-04-11T21:46:07Z&spr=https&sv=2020-08-04&sr=c&sig=uDJgmXncthqqlQvAVpQyNlRjaOuEG9a7jNWXUgZbkQs%3D
      az storage blob exists -c testcontainer -n sample.txt --account-name newstrac1 --sas-token ?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-04-11T21:49:52Z&st=2022-04-11T13:49:52Z&spr=https&sig=oJdxyGC%2BlabLha1NqlJEOnbU5H%2BVhYkJ87kuxRX927U%3D